### ISSUE TITLE
Documentation of an Example

### ISSUE THREAD

**Issue by boldtrn** [intaro/hstore-extension#2]
Hi,

I'd love to use your hstore-extension. However, I wonder if it is ready to use and if you could provide any more examples than shown in the Tests?

Best,
Robin

**Comment by linniksa** [comment]
@boldtrn
Hello, we use this code with php-ext for Coder on production servers and it works fine.
hstore-extension designed to be used with doctrine, but Coder part can be used with any php code if needed.
Can you tell us what examples would be worth adding?

**Comment by boldtrn** [comment]
@linniksa 
Hi, I want to add hstore support to a symfony application. 
A simple example showing a complete entity (I needed to debug your code to find out that you use simple arrays on the PHPSide to represent hstore).
Also a repository class would be nice. I am not sure if you support the QueryBuilder component or do I need to use DQL?
Right now I need to search for the code parts to explain this to my self. Some words and a comment about the stability of the project would be great as well :)

Best,
Robin
