### ISSUE TITLE
Add requiresSQLCommentHint function

### ISSUE THREAD

**Issue by mrysz** [intaro/hstore-extension#8]
In last version of symfony (4.3) I have this warning:

> User Deprecated: The type "hstore" was marked as commented in its configuration but not in the type itself. This is deprecated and will be removed in DoctrineBundle 2.0. Please update the return value of "Intaro\HStore\Doctrine\Types\HStoreType::requiresSQLCommentHint()."

I think simple function should be added to avoid this message:

```
    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return true;
    }
```

**Comment by linniksa** [comment]
fixed by #9
